# Travis CI configuration
slack: nuba-casfee:Drmw9BVf1w7r4wSHCZA1W7tN
language: node_js
sudo: true
cache:
  directories:
    - node
    - node_modules
dist: trusty
node_js:
  - '7.4.0'
before_install:
 - npm install -g @angular/cli@latest
 - npm install -g firebase-tools
 # Eventhough the package.json has zone.js@0.7.2 has a dependency version
 # 0.7.5 is installed instead which causes a test error.
 # Workaround: install 0.7.2 explicitely
 # Remove this workaround once it is fixed here:
 # see https://github.com/angular/zone.js/issues/427
 - npm uninstall zone.js@0.7.5
 - npm install --save zone.js@0.7.2

 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
script:
 - ng build --prod
 - ng lint
 - ng test --watch false # http://mseemann.de/frontend/2016/05/31/setup-angular-2-app-part-1.html
 - ng serve &
 - ng e2e
after_success:
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    firebase deploy --token "$FIREBASE_TOKEN";
  fi
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
